# E01_ Mateo Tavares_Correción

In [81]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import r2_score
from sklearn.linear_model import Ridge
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.api as sm
import numpy as np
from sklearn.linear_model import LinearRegression

## Teórico Corregido.

1.        ¿Qué es un pipeline?
    Es una secuencia de pasos estructurados que permiten automatizar un flujo de trabajo. En nuestro caso es el flujo que se establece para los datos con sus procesos, entradas, y salidas para realizar una regresión de manera apropiada.

2.        ¿Cuál es el propósito de realizar regresiones? 

Extrapolar: Predecir una variable Y fuera del dominio de tus datos.
Interpolar: Predecir una variable Y dentro del dominio de tus datos.


3.        ¿En qué consiste el proceso de escalamiento de factores?
Poner en la misma escala los datos de X, de forma que los coeficientes puedan ser analizados por impacto. Este se hace normalmente de forma estándar, es decir restando la media y dividiendo por la desviación estándar.

4.        Explica el propósito de penalizar factores en una regresión.
Penalizar factores consiste en no permitir que coeficientes no tengan demasiado peso en el modelo, ya que esto puede llevar al overfitting, con las penalizaciones, puedes reducir coeficientes demasiado alejados o también eliminar los que no son significativos.

5.        ¿Cuál es la relación entre escalamiento y penalización?
La penalización es sobre los coeficientes, por tanto si no están en la misma escala, la penalización no podrá identificar si un coeficiente tiene demasiado o muy poco peso.

6.        Explica el concepto de una prueba de hipótesis.
Consiste en demostrar estadísticamente un supuesto de tu muestra sobre la población con un cierto grado de error. 
Se utiliza Ho para expresar una igualdad y Hi para diferente mayor, menor, etc. Consiste entonces en obtener un estadístico (t,z,etc) que demuestre que, en cierto rango, tu muestra es igual, menor, etc, que en tu población.

7.        Explica la interpretación de un p-value de una prueba de hipótesis que compara contra una media µ.
El P value sería la probabilidad de un error tipo 1, es decir, la probabilidad de que rechaces la hipótesis nula y sea verdadera, entonces, es la probabilidad de que yo haya obtenido una muestra extrema y que rechace que es igual por ejemplo, solo porque es poco probable.

8.        Describe el propósito de realizar cross-validation.
Funciona para que el modelo no haga overfit, es decir, ajuste de más a todos los datos y no pueda generalizar a nuevos inputs.

9.        Describe los pasos que seguirías al hacer un análisis exploratorio de datos. Justifica cada paso.
Primero observaría los datos a simple vista, me aseguraría de ver qué significa cada variable y sus unidades, específicamente en este parcial para ver ¿Cuáles son mis X? y ¿Cuál es mi Y?, sacaría también las distribuciones de cada variable, esto me va a indicar cómo se comporta cada una, la media, la desviación estándar en caso de ser numérica para ver las escalar, los valores e interpretar.
10.  ¿Qué es el teorema del límite central?
Dice que los promedios muestrales mientras más grande sea la muestra, más se acercan a formar una distribución normal.

## Ejercicio 1 práctico corregido.

In [82]:
x=np.array([[1,1],[1,1],[3,9]])
y=np.array([[2],[1],[2]])
lr=LinearRegression()
reg1=lr.fit(x,y)

In [83]:

x = np.array([1, 2, 3]).reshape(-1, 1)
y = np.array([2, 1, 2])
x2 = np.hstack([x, x**2])
lr = LinearRegression()
reg1 = lr.fit(x2, y)
print(reg1.coef_)
print(reg1.intercept_)

[-4.  1.]
4.999999999999997

## Ejercicio 3 práctico corregido.

In [84]:
df = pd.read_csv('imdb_top1000_lae.csv')
df.head()

,Unnamed: 0,Series_Title,Released_Year,Certificate,Runtime,IMDB_Rating,Meta_score,Director,Gross,Drama,...,Fantasy,Family,Thriller,Romance,Sci-Fi,War,Music,Musical,Sport,History
0,0,The Shawshank Redemption,1994,A,142 min,9.3,80.0,Frank Darabont,"28,341,469",1,...,0,0,0,0,0,0,0,0,0,0
1,1,The Godfather,1972,A,175 min,9.2,100.0,Francis Ford Coppola,"134,966,411",1,...,0,0,0,0,0,0,0,0,0,0
2,2,The Dark Knight,2008,UA,152 min,9.0,84.0,Christopher Nolan,"534,858,444",1,...,0,0,0,0,0,0,0,0,0,0
3,3,The Godfather: Part II,1974,A,202 min,9.0,90.0,Francis Ford Coppola,"57,300,000",1,...,0,0,0,0,0,0,0,0,0,0
4,4,12 Angry Men,1957,U,96 min,9.0,96.0,Sidney Lumet,"4,360,000",1,...,0,0,0,0,0,0,0,0,0,0

In [85]:
df= df.drop(columns = ['Unnamed: 0'])
df= df.drop(columns = ['Director'])

Eliminé director porque eran demasiadas columnas extra.

In [86]:

df["Runtime"] = df["Runtime"].str.replace(" min", "").astype(int)

In [87]:
df_con_dummies = pd.get_dummies(df, columns=['Certificate'])

In [88]:
bool_cols = df_con_dummies.select_dtypes(include=bool).columns
df_con_dummies[bool_cols] = df_con_dummies[bool_cols].astype(int)

In [89]:
df_con_dummies

,Series_Title,Released_Year,Runtime,IMDB_Rating,Meta_score,Gross,Drama,Crime,Action,Biography,...,Certificate_PG-13,Certificate_Passed,Certificate_R,Certificate_TV-14,Certificate_TV-MA,Certificate_TV-PG,Certificate_U,Certificate_U/A,Certificate_UA,Certificate_Unrated
0,The Shawshank Redemption,1994,142,9.3,80.0,"28,341,469",1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,The Godfather,1972,175,9.2,100.0,"134,966,411",1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2,The Dark Knight,2008,152,9.0,84.0,"534,858,444",1,1,1,0,...,0,0,0,0,0,0,0,0,1,0
3,The Godfather: Part II,1974,202,9.0,90.0,"57,300,000",1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
4,12 Angry Men,1957,96,9.0,96.0,"4,360,000",1,1,0,0,...,0,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,Breakfast at Tiffany's,1961,115,7.6,76.0,NaN,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
996,Giant,1956,201,7.6,84.0,NaN,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
997,From Here to Eternity,1953,118,7.6,85.0,"30,500,000",1,0,0,0,...,0,1,0,0,0,0,0,0,0,0
998,Lifeboat,1944,97,7.6,78.0,NaN,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
999,The 39 Steps,1935,86,7.6,93.0,NaN,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0

In [90]:
df_con_dummies["Gross"] = df_con_dummies["Gross"].replace(",", "", regex=True).astype(float)
df_con_dummies["Released_Year"] = pd.to_numeric(df_con_dummies["Released_Year"], errors="coerce")

In [91]:
df_con_dummies= df_con_dummies.dropna()

In [95]:
from scipy import stats
X = df_con_dummies.drop(columns=["Series_Title", "IMDB_Rating"])
Y = df_con_dummies["IMDB_Rating"]

# Train-Test Split
X_entrenamiento, X_prueba, y_entrenamiento, y_prueba = train_test_split(
    X, Y, test_size=0.6, random_state=137
)

# Escalar
scaler = StandardScaler()
X_entrenamiento_esc = scaler.fit_transform(X_entrenamiento)
X_prueba_esc = scaler.transform(X_prueba)

# Modelo de regresión lineal
modelo = LinearRegression()
modelo.fit(X_entrenamiento_esc, y_entrenamiento)

# R2 en train y test
r2_train = modelo.score(X_entrenamiento_esc, y_entrenamiento)
r2_test = modelo.score(X_prueba_esc, y_prueba)

print("R2 Train:", r2_train)
print("R2 Test:", r2_test)

R2 Train: 0.2912237137702597
R2 Test: 0.02091316827866818

R2 demasiado bajo, existen muchas más variables, más complejas que determinan la calificación de una película.

In [99]:

n = X_entrenamiento_esc.shape[0]
p = X_entrenamiento_esc.shape[1] + 1   
X_train_const = np.hstack([np.ones((n, 1)), X_entrenamiento_esc])
y_train = y_entrenamiento.values


XtX = X_train_const.T @ X_train_const
XtX_pinv = np.linalg.pinv(XtX)
beta_hat = XtX_pinv @ (X_train_const.T @ y_train)


y_hat = X_train_const @ beta_hat
resid = y_train - y_hat

rank_X = np.linalg.matrix_rank(X_train_const)
df_res = n - rank_X
RSS = float(resid @ resid)
sigma2 = RSS / df_res

var_beta = sigma2 * XtX_pinv
se_beta = np.sqrt(np.diag(var_beta))


t_stats = beta_hat / se_beta
p_values = 2 * (1 - stats.t.cdf(np.abs(t_stats), df=df_res))


feature_names = ["Intercepto"] + list(X.columns)
res_df = pd.DataFrame({
    "Termino": feature_names,
    "p_value": p_values
})
res_df.head(34)

C:\Users\mateo\AppData\Local\Temp\ipykernel_13224\3891619018.py:21: RuntimeWarning: invalid value encountered in sqrt
  se_beta = np.sqrt(np.diag(var_beta))

                 Termino   p_value
0             Intercepto  0.000000
1          Released_Year  0.054030
2                Runtime  0.000004
3             Meta_score  0.000004
4                  Gross  0.275186
5                  Drama  0.691196
6                  Crime  0.950174
7                 Action  0.064146
8              Biography  0.087756
9                Western  0.010194
10                Comedy  0.222782
11             Adventure  0.868690
12             Animation  0.083664
13                Horror  0.437938
14               Mystery  0.767516
15             Film-Noir  0.853636
16               Fantasy  0.748710
17                Family  0.266006
18              Thriller  0.351954
19               Romance  0.495856
20                Sci-Fi  0.984960
21                   War  0.987666
22                 Music  0.764756
23               Musical  0.280672
24                 Sport  0.307682
25               History  0.932397
26         Certificate_A  0.022191
27  Certificate_Approved  0.765873
28         Certificate_G  0.238766
29        Certificate_GP       NaN
30        Certificate_PG  0.221120
31     Certificate_PG-13  0.300529
32    Certificate_Passed  0.442578
33         Certificate_R  0.244924

Vemos que casi todas las clasificaciones y géneros son insignificantes, salvo el género western, la duración y el metascore.